### ISSUE TITLE
Cancel still makes Changes 

### ISSUE THREAD

**Issue by speed-of-heat** [Holdi601/JoystickProfiler#12]
Pressing the cancel Button is functionally the same as the Finish Relation Button, as it still makes the changes, they are not abandoned ?

**Comment by Holdi601** [comment]
Yeah, it is badly worded from my part. As its the same window as its to create a new relation, pressing cancel there doesn't add the relation into the final structure. So the cancel was ment for that circumstance. I fixed that in my build, that i removed the finish button and renamed the cancel button into close. But I know maybe someone wants to have some cancellation protection, but that is technically a feature request which i can do in future, but right now i rephrased it to the meaning it should have had already. If you still want the cancel protection feel free to make it as a feature request. Otherwise this is "fixed" however you want to take it for the next release to be less misunderstood.
