### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by speed-of-heat** [Holdi601/JoystickProfiler#13]
Firstly let me applaud you for including automatic update , a feature I wish many others would follow you with.

But it just seems to hang, and you have no feedback on how far the process is along or of it  is running at all or how long its going to take to finish? 

Could you put some UI on this so we have an idea of what's going on, many thanks for all of this!

**Comment by Holdi601** [comment]
Yeah I could put some UI there and run it asynchrously. Thus far, I didn't thought it to be necessary as the Builds as of now are just 2-3mb large which should take just a few seconds and a short hang might not even be notice due to the short download and unzip time, even with a fairly slow internet. But I can see the slower the internet the more annoying the process might be.

**Comment by speed-of-heat** [comment]
I have pretty fast internet, i think i got into an odd state, as  i started joypro without one of my devices enabled ... and the UI got "trapped" ... i ended up having to clear out some temp files and reinstalling joypro

**Comment by Holdi601** [comment]
Sounds like it failed closing itself and then couldn't overwrite itself.

**Comment by speed-of-heat** [comment]
yes that sounds about right

**Comment by Holdi601** [comment]
reworked the updater hope its okay now.

**Comment by speed-of-heat** [comment]
lets find out  :)

**Comment by speed-of-heat** [comment]
yep seems to work like a charm!
