### ISSUE TITLE
JoyPro crashes on "Cut DCS Stick specific Defaults" 

### ISSUE THREAD

**Issue by tijmenvn** [Holdi601/JoystickProfiler#59]
I just converted an old Profile to one with a new Throttle, exporting this profile to DCS seems to add all DCS defaults.

Knowing there is an option for this in JoyPro, I try to execute "Cut DCS Stick specific Defaults". Only every attempt makes JoyPro crash.

I hope the following Exception handlers might help out:
[20230810193446.UnhandledException.zip](https://github.com/Holdi601/JoystickProfiler/files/12316626/20230810193446.UnhandledException.zip)

**Comment by Holdi601** [comment]
Deselect In export window star citizen(the one on the bottom not the all or none one. It will be fixed in next version.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Tijmen van ***@***.***>
Sent: Thursday, 10 August 2023 21:34
To: ***@***.***>
Cc: ***@***.***>
Subject: [Holdi601/JoystickProfiler] JoyPro crashes on "Cut DCS Stick specific Defaults" (Issue #59)


I just converted an old Profile to one with a new Throttle, exporting this profile to DCS seems to add all DCS defaults.

Knowing there is an option for this in JoyPro, I try to execute "Cut DCS Stick specific Defaults". Only every attempt makes JoyPro crash.

I hope the following Exception handlers might help out:
20230810193446.UnhandledException.zip<https://github.com/Holdi601/JoystickProfiler/files/12316626/20230810193446.UnhandledException.zip>

**Comment by tijmenvn** [comment]
Star Citizen export has always been disabled and was never selected in my export window.

I did eventually manage to fix it with the following steps:
 - Refresh DCS Clean DB
 - Refresh DCS ID DB
 - Export again

It seems JoyPro had some old DCS Stick specific defaults it was trying to remove? Not sure if that was the case, my setup at least seems to be back in working condition.

Thanks for the quick reply!
